version: '3.1'

services:

  production-nginx-container:
    container_name: 'production-nginx-container'
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./production.conf:/etc/nginx/conf.d/default.conf

    networks:
      - docker-network
    depends_on:
      - webapp

  webapp:
    image: tidymilla/solid-potato:latest
    environment:
      - DATABASE_URL=[_ommited_]
    networks:
      - docker-network
    command: ["./boot.sh"]

networks:
  docker-network:
    driver: bridge
