version: '3.1'

services:

  server:
    image: tidymilla/solid-potato:latest
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - docker-network
    command: ["./boot.sh"]
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:7.0.0
    ports:
      - 9200:9200
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
