"""empty message

Revision ID: bb8d4d9a9c59
Revises: b24292c29030
Create Date: 2019-04-25 14:40:22.368958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb8d4d9a9c59'
down_revision = 'b24292c29030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_priority',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['feature_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('client_id', 'priority')
    )
    op.drop_table('feature_request')
    op.add_column('feature', sa.Column('client_id', sa.Integer(), nullable=True))
    op.add_column('feature', sa.Column('priority', sa.Integer(), nullable=True))
    op.add_column('feature', sa.Column('target_date', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'feature', 'client', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feature', type_='foreignkey')
    op.drop_column('feature', 'target_date')
    op.drop_column('feature', 'priority')
    op.drop_column('feature', 'client_id')
    op.create_table('feature_request',
    sa.Column('feature_id', sa.INTEGER(), nullable=False),
    sa.Column('client_id', sa.INTEGER(), nullable=False),
    sa.Column('priority', sa.INTEGER(), nullable=True),
    sa.Column('target_date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['feature_id'], ['feature.id'], ),
    sa.PrimaryKeyConstraint('feature_id', 'client_id')
    )
    op.drop_table('client_priority')
    # ### end Alembic commands ###
