"""empty message

Revision ID: e10ec7dce2ea
Revises: 
Create Date: 2019-04-25 23:31:22.743849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e10ec7dce2ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_name'), 'client', ['name'], unique=True)
    op.create_table('product_area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_area_name'), 'product_area', ['name'], unique=True)
    op.create_table('feature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('product_area_id', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['product_area_id'], ['product_area.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_title'), 'feature', ['title'], unique=True)
    op.create_table('client_priority',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['feature_id'], ['feature.id'], ),
    sa.PrimaryKeyConstraint('client_id', 'priority')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_priority')
    op.drop_index(op.f('ix_feature_title'), table_name='feature')
    op.drop_table('feature')
    op.drop_index(op.f('ix_product_area_name'), table_name='product_area')
    op.drop_table('product_area')
    op.drop_index(op.f('ix_client_name'), table_name='client')
    op.drop_table('client')
    # ### end Alembic commands ###
